server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: gateway
          uri: https://github.com/satanas66/microservicios-tutorial
          search-paths: config-data
  application:
    name: config-service           
  

